name: Test

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          check-latest: true
      - run: npm ci
        env: 
          NODE_AUTH_TOKEN: ${{secrets.READ_PACKAGE_TOKEN}}
      - run: npm test
